BEGIN;

INSERT INTO infra.ingestion_file_registry (
    source_system,
    source_object,
    raw_table,
    s3_bucket,
    s3_key,
    file_size_bytes,
    file_checksum,
    status,
    rows_loaded,
    started_at,
    finished_at
)
VALUES (
    'money_flow_app',
    'money_flow',
    'raw.money_flow',
    'ci-bucket',
    'ci/money_flow.csv',
    0,
    'ci-checksum',
    'loaded',
    5,
    NOW(),
    NOW()
);

INSERT INTO raw.money_flow (
    source_number,
    transaction_date,
    account,
    amount,
    currency,
    parent_category,
    subcategory,
    category,
    counterparty,
    transfer_account,
    transfer_amount,
    transfer_currency,
    tags,
    place,
    note,
    source_file,
    ingestion_id
)
VALUES
    (
        '1',
        '2026-08-01 10:00:00',
        'Arthas',
        '1000',
        'USD',
        'Income',
        NULL,
        'Salary',
        'Employer',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'CI income transaction',
        'ci/money_flow.csv',
        1
    ),
    (
        '2',
        '2026-08-02 11:00:00',
        'Arthas',
        '-100',
        'USD',
        'Expenses',
        'Food',
        'Groceries',
        'CI Store',
        NULL,
        NULL,
        NULL,
        'Регулярные траты',
        'CI Location',
        'CI regular expense',
        'ci/money_flow.csv',
        1
    ),
    (
        '3',
        '2026-08-03 12:00:00',
        'Pandaren Brewmaster',
        '-50',
        'USD',
        'Expenses',
        'Reserve',
        'Reserve Expense',
        NULL,
        NULL,
        NULL,
        NULL,
        'Расход резерва',
        NULL,
        'CI reserve expense',
        'ci/money_flow.csv',
        1
    ),
    (
        '4',
        '2026-08-04 13:00:00',
        'Thrall',
        '-300',
        'RUB',
        'Transfers',
        NULL,
        'Account Transfer',
        NULL,
        'Archimond',
        '5',
        'USD',
        NULL,
        NULL,
        'CI transfer',
        'ci/money_flow.csv',
        1
    ),
    (
        '5',
        '2026-08-05 14:00:00',
        'Archimond',
        '0',
        'USD',
        'Adjustments',
        NULL,
        'Adjustment',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'CI zero transaction',
        'ci/money_flow.csv',
        1
    );

COMMIT;
